services:
  langflow:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    user: root
    ports:
      - "127.0.0.1:7860:7860"
    depends_on:
     - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - LANGFLOW_CONFIG_DIR=/app/langflow
#      - LANGFLOW_LOAD_FLOWS_PATH=/app/langflow/templates/starter_projects
      - DO_NOT_TRACK=true                  # the envâ€‘var you asked for
    volumes:
      - ./langflow-data:/app/langflow   # host folder

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
